site_name: 'CoderDojo Mentor Resources'
nav:
  - Introduction: index.md
  - Code Groups: code-groups.md
  - Code Group Content Status: code-group-status.md 
  - Code of Conduct: code-of-conduct.md
  - Mentoring Best Practices: mentoring-best-practices.md
  - Beginning Concepts: beginning-concepts.md
  - Content Authoring Guide: content-authoring-guide.md
  - Journey Maps: journey-maps.md
  - Designing Concept Cards: designing-concept-cards.md
  - Resources: resources.md
  - Contact Us: contact.md

repo_name: 'CoderDojoTC'
repo_url: 'https://github.com/CoderDojoTC/CoderDojoTC'
edit_uri: 'blob/master/docs'
copyright: 'All content is licensed under Creative Commons Sharealike non-commercial with attribution'
theme:
  name: material
  logo: img/coderdojo-logo.jpg
  favicon: img/favicon.png
  palette:
    primary: '#642580'
    accent: '#41BAC1'

  feature:
    tabs: true
  custom_dir: 'theme'
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - codehilite:
      linenums: true
